Gjennomgått med egne kommentarer
NorskHelsenett/Tillitsrammeverk pull request #35
Opened 2023-03-03 12:21 UTC by troelde

@steinarnoem : Du får se igjennom her, og så får vi ta en diskusjon.

Noen spørsmål og kommentarer.

Trond

2023-03-08 09:10 UTC, steinarnoem requested changes
Hei Trond! Jeg har gjennomført en review av committen din.
Mye bra her altså - takk :)

Hvis du kan se igjennom tilbakemeldingene mine,  og gjøre de endringene jeg ber om kan du sende en ny pull-request som jeg kan committe :)

Elsker at du bidrar!

2023-03-08 09:10 UTC, steinarnoem commented on specs/informasjons_og_datamodell.md
> +> Kommentar TRE: Tenker det er greit å ta en runde på hva konkret _validering_ og _kontrollering_ faktisk innebærer. Når vi ser på [attributtmodellen til HSØ](https://github.com/HL7Norway/AuditEvent/
Også fint om du kan fjerne kommentaren fra dokumentet før vi committer.

2023-03-08 09:10 UTC, steinarnoem commented on specs/informasjons_og_datamodell.md
> +> Kommentar TRE: JWT og SAML-tokens transporteres i en HTTPS request i hhv. HTTP Authorization Header og HTTP Body som Header i SOAP-melding. Sistnevnte er da like godt/dårlig beskyttet som selve pay
Kjempebra innspill, og veldig i tråd med vår forståelse i NHN. 
Det vil bli gjennomført en DPIA, hvor vi i etterkant må se på sikkerhetstiltak. Jeg tror vi må gjøre en risikovurdering før vi bestemmer oss for sikkerhetstiltak, f.eks. må vi forstå hvor stor risiko det faktisk er knyttet til terminering av TLS før vi innfører kryptering av tokens. Personlig mener jeg at man har andre utfordringer dersom TLS termineres ett sted hvor man ikke har kontroll på logging.

Fint om du kan fjerne kommentaren, og opprette en ny diskusjon eller et issue som er knyttet til spesifikasjonen om bruk av OIDC og OAuth. Jeg mener at vi må peke på eventuelle personvernsutfordringer i informasjonsmodellen, men skille diskusjonene om risiko og tiltak fra selve spesifikasjonen som et eget tema.

2023-03-09 08:47 UTC, troelde commented on specs/informasjons_og_datamodell.md
> +Spesifikasjonen beskriver også hvilke konkrete attributter som skal brukes for å beskrive informasjonsmodellen i form av en datamodell. Datamodellen beskriver også hvilke verdier (mer konkret kodever
Ja, det blir nok begge deler. Reformulerer i ny pull request.

2023-03-09 08:52 UTC, troelde commented on specs/informasjons_og_datamodell.md
> +##### 3.2.5.1 Identifikator for helsepersonellet som "fysisk person" (Entitet: Helsepersonell)
Det var bare det at det var vanskelig å skjønner at dette avsnittet handlet om entitet helsepersonell slik jeg forstår det.  Har lagt det inn i teksten i ny pull-request.

2023-03-09 09:12 UTC, closed without merging

2023-03-09 12:04 UTC, troelde commented on specs/informasjons_og_datamodell.md
> +Datamodellen skal brukes i sikkerhetsbilletter/-bevis (token) som skal behandles av mange aktører og i mange systemer. Aktørene som mottar og behandler sikkerhetsbillettene må ha svært høy tillit til
@troelde : Lager issue på ordliste/begrepskapittel

2023-03-09 12:05 UTC, troelde commented on specs/informasjons_og_datamodell.md
> +| "structural_role" | Indikerer hvorvidt dette er et helsepersonell med/uten lisens/autorisasjon eller person med sekretærfunksjon (Trond: Finner ikke denne i datamodellen) | Konsumentens EPJ | **Ja*
Fjerner hele endring

2023-03-09 12:08 UTC, troelde commented on specs/informasjons_og_datamodell.md
> +> Kommentar Trond E> Skulle gjerne få mappet dennne fra HSØ sin [attributtliste](https://github.com/HL7Norway/AuditEvent/blob/main/attributtliste.md).
Fjerner endring